pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - status-success~=Validate a Pull Request
      - author=dependabot[bot]
    actions:
      merge:
        method: merge

  - name: Label dependabot PRs
    conditions:
      - author=dependabot[bot]
    actions:
      label:
        add: ["dependencies"]

  - name: Delete the PR branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
